package igu;

import java.awt.Image;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeParseException;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import logica.Cita;
import utils.FormUtils;
import logica.Mascotas;
import logica.Servicios; 
import controlador.ControlCitas;
import controlador.ControlMascotas;
import controlador.ControlServicios;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 * Clase que representa la ventana principal de gestión de citas en la
 * aplicación.
 * <p>
 * Esta clase extiende {@link javax.swing.JFrame} y permite al usuario
 * visualizar, crear, modificar y eliminar citas de mascotas. Incluye
 * validaciones básicas de campos, gestión de servicios y control de la interfaz
 * según el rol del usuario.
 * </p>
 *
 * <p>
 * Contiene referencias a las clases de control:
 * <ul>
 * <li>{@link Controladora} para la lógica de negocio.</li>
 * <li>{@link ControladoraPersistencia} para operaciones de base de datos.</li>
 * </ul>
 *
 * Campos importantes:
 * <ul>
 * <li>{@code boolean vacio}: bandera de validación para saber si los campos
 * están vacíos.</li>
 * <li>{@code String rolActual}: almacena el rol del usuario que abrió la
 * ventana.</li>
 * </ul>
 *
 * @author TuNombre
 * @version 1.0
 */
public class FrmCitas extends javax.swing.JFrame {

    /**
     * LLamamiento a la clase Controladora
     */
    ControlCitas controlCitas = null;
    ControlMascotas controlMascotas = null;
    ControlServicios controlServicios = null;

    /**
     * Rol del usuario que abrió la ventana (Ej. "Recepcionista", "Trabajador").
     */
    private String rolActual;

    /**
     * Constructor de la ventana FrmCitas.
     * <p>
     * Inicializa los componentes gráficos, la lógica de control y la
     * persistencia. Configura el ícono de la ventana y centra la ventana en la
     * pantalla.
     * </p>
     *
     * @param rol el rol del usuario que abrirá la ventana, utilizado para
     * controlar la interfaz y permisos
     */
    public FrmCitas(String rol) {
        controlCitas = new ControlCitas();
        controlServicios = new ControlServicios();
        controlMascotas = new ControlMascotas();
        initComponents();
        setLocationRelativeTo(null);
        Image icon = new ImageIcon("./icon/logo2.png").getImage();
        this.setIconImage(icon);
        this.rolActual = rol;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCitas = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cmbMascota1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jsFecha = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaServicios = new javax.swing.JList<Servicios>() ;
        jLabel1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnVerTodo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Citas - Administrador  - Recepcionista");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCitasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCitas);

        btnLimpiar.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\limpiar.png")); // NOI18N
        btnLimpiar.setText("  Limpiar");
        btnLimpiar.setToolTipText("Limpiar los campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\guardar.png")); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("Guardar citas");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\salir.png")); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cmbMascota1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mascotas"));
        cmbMascota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMascota1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha / Hora:");

        jsFecha.setModel(new javax.swing.SpinnerDateModel());

        listaServicios.setBorder(javax.swing.BorderFactory.createTitledBorder("Servicios:"));
        listaServicios.setModel(new DefaultListModel<Servicios>());
        jScrollPane3.setViewportView(listaServicios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jsFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(cmbMascota1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jsFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(cmbMascota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel1.setText("Citas");

        btnEliminar.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\eliminar.png")); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("Eliminar Citas");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\buscar1.png")); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("Buscar por fecha");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnVerTodo.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btnVerTodo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\cita.png")); // NOI18N
        btnVerTodo.setText("Ver Todo");
        btnVerTodo.setToolTipText("Ver todos las citas");
        btnVerTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTodoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\editar.png")); // NOI18N
        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(254, 254, 254)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerTodo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnVerTodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        FormUtils.salirSegunRol(rolActual, this);  // según el rol saldrá una ventana u otra
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        FormUtils.limpiarFormulario(rootPane);  // limpiar los campos
        cargarTabla();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarCitas();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarMascotas();
        cargarServicios();
        cargarTabla();
    }//GEN-LAST:event_formWindowOpened

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            eliminarCita();
        } catch (Exception ex) {
            Logger.getLogger(FrmCitas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarFecha();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVerTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTodoActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnVerTodoActionPerformed

    private void cmbMascota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMascota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMascota1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            editarCitas();
        } catch (Exception ex) {
            Logger.getLogger(FrmCitas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblCitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCitasMouseClicked
        clickTablaCita();
    }//GEN-LAST:event_tblCitasMouseClicked
/**
 * 
 * @throws Exception 
 */
    private void eliminarCita() throws Exception {
        int fila = tblCitas.getSelectedRow();
        if (fila == -1) {
            return;
        }

        int id = (int) tblCitas.getValueAt(fila, 0);
        controlCitas.eliminarCita(id);
        cargarTabla();
       
    }

    private void buscarFecha() {
        String fechaStr = JOptionPane.showInputDialog(this, "Introduce la fecha (yyyy-MM-dd):");

        if (fechaStr == null || fechaStr.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se introdujo ninguna fecha.");
            cargarTabla();
            return;
        }

        try {
            LocalDate fecha = LocalDate.parse(fechaStr.trim());
            List<Cita> lista = controlCitas.buscarPorFecha(fecha);

            DefaultTableModel modelo = (DefaultTableModel) tblCitas.getModel();
            modelo.setRowCount(0);

            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron citas para ese día: " + fecha);
                return;
            }

            for (Cita c : lista) {
                String serviciosTexto = controlCitas.convertirServiciosTexto(c);

                modelo.addRow(new Object[]{
                    c.getId(),
                    c.getFechaHora(),
                    c.getMascota().getNombreMas(),
                    serviciosTexto
                });
            }

        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Usa yyyy-MM-dd.");
            cargarTabla();
        }
    }

    /**
     * Carga los datos de las citas en la tabla {@code tblCitas}.
     * <p>
     * Este método realiza las siguientes acciones:
     * <ul>
     * <li>Crea un modelo de tabla {@link DefaultTableModel} que no permite
     * edición en las celdas.</li>
     * <li>Recorre la lista de {@link Cita} obtenida desde
     * {@code control.traerCitas()}.</li>
     * <li>Convierte la lista de servicios de cada cita en un texto legible. Si
     * no tiene servicios, se muestra "Sin Servicios".</li>
     * <li>Agrega cada cita como una fila en la tabla con columnas: ID,
     * Fecha/Hora, Mascota y Servicios.</li>
     * <li>Ajusta el ancho de las columnas según la importancia de la
     * información.</li>
     * </ul>
     */
    private void cargarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
                new String[]{"ID", "Fecha/Hora", "Mascota", "Servicios"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (Cita c : controlCitas.traerCitas()) {

            String serviciosTexto = controlCitas.convertirServiciosTexto(c);

            modelo.addRow(new Object[]{
                c.getId(),
                c.getFechaHora(),
                c.getMascota().getNombreMas(),
                serviciosTexto
            });
        }

        tblCitas.setModel(modelo);

        TableColumnModel columnModel = tblCitas.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(40);
        columnModel.getColumn(0).setMinWidth(40);
        columnModel.getColumn(0).setMaxWidth(40);
        columnModel.getColumn(1).setPreferredWidth(150);
        columnModel.getColumn(2).setPreferredWidth(100);
        columnModel.getColumn(3).setPreferredWidth(300);
        columnModel.getColumn(3).setMinWidth(200);
         FormUtils.limpiarFormulario(this);
    }

    private void clickTablaCita() {
        int fila = tblCitas.getSelectedRow();
        if (fila == -1) {
            return;
        }

        int idCita = (int) tblCitas.getValueAt(fila, 0);
        Cita cita = controlCitas.traerCita(idCita);

        cmbMascota1.setSelectedItem(cita.getMascota().getNombreMas());

        Date fecha = Date.from(cita.getFechaHora()
                .atZone(ZoneId.systemDefault()).toInstant());
        jsFecha.setValue(fecha);

        listaServicios.clearSelection();
        DefaultListModel<Servicios> modelo = (DefaultListModel<Servicios>) listaServicios.getModel();

        for (int i = 0; i < modelo.size(); i++) {
            if (cita.getServicio().contains(modelo.get(i))) {
                listaServicios.addSelectionInterval(i, i);
            }
        }
    }

    private Map<String, Mascotas> indexMascotas = new HashMap<>();

    /**
     * Carga los datos de las citas en la tabla {@code tblCitas}.
     * <p>
     * Este método realiza las siguientes acciones:
     * <ul>
     * <li>Crea un modelo de tabla {@link DefaultTableModel} que no permite
     * edición en las celdas.</li>
     * <li>Recorre la lista de {@link Cita} obtenida desde
     * {@code control.traerCitas()}.</li>
     * <li>Convierte la lista de servicios de cada cita en un texto legible. Si
     * no tiene servicios, se muestra "Sin Servicios".</li>
     * <li>Agrega cada cita como una fila en la tabla con columnas: ID,
     * Fecha/Hora, Mascota y Servicios.</li>
     * <li>Ajusta el ancho de las columnas según la importancia de la
     * información.</li>
     * </ul>
     */
    private void cargarMascotas() {

        List<Mascotas> listaMascotas = controlMascotas.traerMascotas();
        cmbMascota1.removeAllItems(); // limpiar antes
        indexMascotas.clear();        // limpiar el mapa también

        for (Mascotas m : listaMascotas) {
            cmbMascota1.addItem(m.getNombreMas());
            indexMascotas.put(m.getNombreMas(), m);
        }

    }

    private void cargarServicios() {
        listaServicios.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        DefaultListModel<Servicios> modelo = new DefaultListModel<>();
        for (Servicios s : controlServicios.traerServicios()) {
            modelo.addElement(s);
        }
        listaServicios.setModel(modelo);

    }

    private void guardarCitas() {
        Mascotas mascota = indexMascotas.get(cmbMascota1.getSelectedItem());
        LocalDateTime fecha = controlCitas.convertirFecha((Date) jsFecha.getValue());
        List<Servicios> servicios = listaServicios.getSelectedValuesList();

        controlCitas.guardarCita(mascota.getNum_cliente(), fecha, servicios);
        cargarTabla();
    }

    // BOTÓN EDITAR
    private void editarCitas() throws Exception {
        int fila = tblCitas.getSelectedRow();
        if (fila == -1) {
            return;
        }

        int id = (int) tblCitas.getValueAt(fila, 0);
        Mascotas mascota = indexMascotas.get(cmbMascota1.getSelectedItem());
        LocalDateTime fecha = controlCitas.convertirFecha((Date) jsFecha.getValue());
        List<Servicios> servicios = listaServicios.getSelectedValuesList();

        controlCitas.editarCita(id, mascota, fecha, servicios);
        cargarTabla();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerTodo;
    private javax.swing.JComboBox<String> cmbMascota1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jsFecha;
    private javax.swing.JList<Servicios> listaServicios;
    private javax.swing.JTable tblCitas;
    // End of variables declaration//GEN-END:variables
}
