package igu;

import java.awt.Font;
import java.awt.Image;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import logica.Cita;
import logica.Controladora;
import logica.FormUtils;
import logica.Mascotas;
import logica.Servicios;
import persistencia.CitaJpaController;
import persistencia.ControladoraPersistencia;

/**
 * Clase que representa la ventana principal de gestión de citas en la
 * aplicación.
 * <p>
 * Esta clase extiende {@link javax.swing.JFrame} y permite al usuario
 * visualizar, crear, modificar y eliminar citas de mascotas. Incluye
 * validaciones básicas de campos, gestión de servicios y control de la interfaz
 * según el rol del usuario.
 * </p>
 *
 * <p>
 * Contiene referencias a las clases de control:
 * <ul>
 * <li>{@link Controladora} para la lógica de negocio.</li>
 * <li>{@link ControladoraPersistencia} para operaciones de base de datos.</li>
 * </ul>
 *
 * Campos importantes:
 * <ul>
 * <li>{@code boolean vacio}: bandera de validación para saber si los campos
 * están vacíos.</li>
 * <li>{@code String rolActual}: almacena el rol del usuario que abrió la
 * ventana.</li>
 * </ul>
 *
 * @author TuNombre
 * @version 1.0
 */
public class FrmCitas extends javax.swing.JFrame {

    /**
     * LLamamiento a la clase Controladora
     */
    Controladora control = null;

     /**
     * LLamamiento a la clase ControladoraPersistencia
     */
    ControladoraPersistencia controlPersis = null;

    /**
     * Bandera de validación que indica si los campos están vacíos. Inicialmente
     * se establece en false.
     */
    boolean vacio = false;      // boolean para validar con valor false si en los campos se han introducido datos

    /**
     * Rol del usuario que abrió la ventana (Ej. "Recepcionista", "Trabajador").
     */
    private String rolActual;

    /**
     * Constructor de la ventana FrmCitas.
     * <p>
     * Inicializa los componentes gráficos, la lógica de control y la
     * persistencia. Configura el ícono de la ventana y centra la ventana en la
     * pantalla.
     * </p>
     *
     * @param rol el rol del usuario que abrirá la ventana, utilizado para
     * controlar la interfaz y permisos
     */
    public FrmCitas(String rol) {
        control = new Controladora();
        controlPersis = new ControladoraPersistencia();
        initComponents();
        setLocationRelativeTo(null);
        Image icon = new ImageIcon("./icon/logo2.png").getImage();
        this.setIconImage(icon);
        this.rolActual = rol;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCitas = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cmbMascota1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jBoxBanio = new javax.swing.JCheckBox();
        jBoxCorte = new javax.swing.JCheckBox();
        jBoxUnias = new javax.swing.JCheckBox();
        jsFecha = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnVerTodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Citas - Administrador  - Recepcionista");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCitas);

        btnLimpiar.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\limpiar.png")); // NOI18N
        btnLimpiar.setText("  Limpiar");
        btnLimpiar.setToolTipText("Limpiar los campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\guardar.png")); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("Guardar citas");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\salir.png")); // NOI18N
        btnSalir.setText("Atras");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cmbMascota1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mascotas"));

        jLabel2.setText("Fecha / Hora:");

        jLabel11.setText("Servicios:");
        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBoxBanio.setBackground(new java.awt.Color(204, 204, 255));
        jBoxBanio.setText("Baño");
        jBoxBanio.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBoxCorte.setBackground(new java.awt.Color(204, 204, 255));
        jBoxCorte.setText("Corte");
        jBoxCorte.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBoxUnias.setBackground(new java.awt.Color(204, 204, 255));
        jBoxUnias.setText("Uñas");
        jBoxUnias.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jsFecha.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jsFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBoxBanio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBoxCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBoxUnias, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbMascota1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jsFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jBoxBanio)
                    .addComponent(jBoxCorte)
                    .addComponent(jBoxUnias))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbMascota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel1.setText("Citas");

        btnEliminar.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\eliminar.png")); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("Eliminar Citas");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\buscar1.png")); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("Buscar por fecha");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnVerTodo.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btnVerTodo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\cita.png")); // NOI18N
        btnVerTodo.setText("Ver Todo");
        btnVerTodo.setToolTipText("Ver todos las citas");
        btnVerTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerTodo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnVerTodo, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        FormUtils.salirSegunRol(rolActual, this);  // según el rol saldrá una ventana u otra
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        FormUtils.limpiarFormulario(rootPane);  // limpiar los campos
        cargarTabla();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarCitas();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarMascotas();
        cargarTabla();
    }//GEN-LAST:event_formWindowOpened

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarCita();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarFecha();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVerTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTodoActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnVerTodoActionPerformed

    /**
     * Elimina la cita seleccionada en la tabla {@code tblCitas}.
     * <p>
     * Este método verifica si el usuario ha seleccionado una fila en la tabla.
     * Si no hay selección, se muestra un mensaje solicitando seleccionar una
     * cita. Si hay una fila seleccionada, se obtiene el ID de la cita y se
     * solicita confirmación al usuario mediante un cuadro de diálogo.
     * </p>
     * <p>
     * Si el usuario confirma la eliminación, se llama al método
     * {@code eliminarCita} del controlador para eliminar la cita de la base de
     * datos. Luego se muestra un mensaje de éxito y se recarga la tabla para
     * reflejar los cambios. En caso de error durante la eliminación, se muestra
     * un mensaje con la descripción del error.
     * </p>
     */
    private void eliminarCita() {
        int filaSeleccionada = tblCitas.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una cita para eliminar");
            return;
        }

        // Obtener el ID de la cita desde la tabla
        int idCita = (int) tblCitas.getValueAt(filaSeleccionada, 0);

        // Confirmación
        int opcion = JOptionPane.showConfirmDialog(this,
                "¿Seguro que deseas eliminar la cita seleccionada?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            try {
                control.eliminarCita(idCita);
                JOptionPane.showMessageDialog(this, "Cita eliminada correctamente");
                cargarTabla(); // refrescar la tabla
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar cita: " + e.getMessage());
            }
        }
    }

    /**
     * Permite buscar citas en la tabla según una fecha específica ingresada por
     * el usuario.
     * <p>
     * Este método solicita al usuario que introduzca una fecha en formato
     * "yyyy-MM-dd" mediante un cuadro de diálogo. Luego convierte la cadena
     * ingresada a un objeto {@link LocalDate} y utiliza el
     * {@link CitaJpaController} para obtener las citas que coincidan con esa
     * fecha.
     * </p>
     * <p>
     * Si se encuentran citas, se muestran en {@code tblCitas} incluyendo los
     * servicios asociados a cada cita. Si no hay coincidencias, se muestra un
     * mensaje informando que no se encontraron citas para la fecha indicada. Si
     * el formato de la fecha es incorrecto, se muestra un mensaje de error y se
     * recarga la tabla con todas las citas.
     * </p>
     * <p>
     * En caso de que el usuario no ingrese ninguna fecha, se muestra un mensaje
     * indicando la falta de entrada y se recarga la tabla con todas las citas.
     * </p>
     */
    private void buscarFecha() {
        String fechaStr = JOptionPane.showInputDialog(this, "Introduce la fecha (yyyy-MM-dd):");

        if (fechaStr != null && !fechaStr.trim().isEmpty()) {
            try {
                LocalDate fecha = LocalDate.parse(fechaStr.trim()); // convierte String a LocalDate
                CitaJpaController controlCita = new CitaJpaController();
                List<Cita> lista = controlCita.findCitasByFecha(fecha);
                DefaultTableModel modelo = (DefaultTableModel) tblCitas.getModel();

                modelo.setRowCount(0); // Limpiar tabla

                if (lista.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No se encontraron citas para ese día: " + fecha);
                } else {
                    for (Cita c : lista) {
                        // Construir un string con todos los servicios de la mascota
                        String serviciosTexto = "Sin servicios";
                        if (c.getServicio() != null && !c.getServicio().isEmpty()) {
                            StringBuilder sb = new StringBuilder();
                            for (Servicios s : c.getServicio()) {
                                sb.append(s.getTipoServicios())
                                        .append(" (")
                                        .append(s.getPrecio())
                                        .append("€), ");
                            }
                            serviciosTexto = sb.substring(0, sb.length() - 2); // quitar coma final
                        }

                        // Añadir fila a la tabla incluyendo los servicios
                        modelo.addRow(new Object[]{
                            c.getId(),
                            c.getFechaHora(),
                            c.getMascota().getNombreMas(),
                            serviciosTexto
                        });
                    }
                }
            } catch (DateTimeParseException e) {
                JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Usa yyyy-MM-dd.");
                cargarTabla();
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se introdujo ninguna fecha.");
            cargarTabla();
        }
    }

    /**
     * Carga los datos de las citas en la tabla {@code tblCitas}.
     * <p>
     * Este método realiza las siguientes acciones:
     * <ul>
     * <li>Crea un modelo de tabla {@link DefaultTableModel} que no permite
     * edición en las celdas.</li>
     * <li>Recorre la lista de {@link Cita} obtenida desde
     * {@code control.traerCitas()}.</li>
     * <li>Convierte la lista de servicios de cada cita en un texto legible. Si
     * no tiene servicios, se muestra "Sin Servicios".</li>
     * <li>Agrega cada cita como una fila en la tabla con columnas: ID,
     * Fecha/Hora, Mascota y Servicios.</li>
     * <li>Ajusta el ancho de las columnas según la importancia de la
     * información.</li>
     * </ul>
     */
    private void cargarTabla() {
        // Modelo de tabla que no permite edición en las celdas
        DefaultTableModel modelo = new DefaultTableModel(
                new String[]{"ID", "Fecha/Hora", "Mascota", "Servicios"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // todas las celdas no editables
            }
        };

        for (Cita c : control.traerCitas()) {
            // Convertir la lista de servicios en un texto legible
            String serviciosTexto = "Sin Servicios";
            if (c.getServicio() != null && !c.getServicio().isEmpty()) {
                StringBuilder sb = new StringBuilder();
                for (Servicios s : c.getServicio()) {
                    sb.append(s.getTipoServicios())
                            .append(" (")
                            .append(s.getPrecio())
                            .append("€), ");
                }
                serviciosTexto = sb.substring(0, sb.length() - 2); // quitar coma final
            }

            modelo.addRow(new Object[]{
                c.getId(),
                c.getFechaHora(),
                c.getMascota().getNombreMas(),
                serviciosTexto
            });
        }

        tblCitas.setModel(modelo);
        // Ajustes de ancho de columnas
        TableColumnModel columnModel = tblCitas.getColumnModel();

        columnModel.getColumn(0).setPreferredWidth(40);
        columnModel.getColumn(0).setMinWidth(40);
        columnModel.getColumn(0).setMaxWidth(40);

        columnModel.getColumn(1).setPreferredWidth(150);

        columnModel.getColumn(2).setPreferredWidth(100);

        columnModel.getColumn(3).setPreferredWidth(300);
        columnModel.getColumn(3).setMinWidth(200);
    }

    private Map<String, Mascotas> indexMascotas = new HashMap<>();

    /**
     * Carga los datos de las citas en la tabla {@code tblCitas}.
     * <p>
     * Este método realiza las siguientes acciones:
     * <ul>
     * <li>Crea un modelo de tabla {@link DefaultTableModel} que no permite
     * edición en las celdas.</li>
     * <li>Recorre la lista de {@link Cita} obtenida desde
     * {@code control.traerCitas()}.</li>
     * <li>Convierte la lista de servicios de cada cita en un texto legible. Si
     * no tiene servicios, se muestra "Sin Servicios".</li>
     * <li>Agrega cada cita como una fila en la tabla con columnas: ID,
     * Fecha/Hora, Mascota y Servicios.</li>
     * <li>Ajusta el ancho de las columnas según la importancia de la
     * información.</li>
     * </ul>
     */
    private void cargarMascotas() {
        List<Mascotas> listaMascotas = control.traerMascotas();
        cmbMascota1.removeAllItems(); // limpiar antes
        indexMascotas.clear();        // limpiar el mapa también

        for (Mascotas m : listaMascotas) {
            cmbMascota1.addItem(m.getNombreMas());
            indexMascotas.put(m.getNombreMas(), m);
        }

    }

    /**
     * Guarda una nueva cita en la base de datos a partir de los datos
     * ingresados en la interfaz.
     * <p>
     * Este método realiza las siguientes acciones:
     * <ul>
     * <li>Obtiene la fecha seleccionada desde el {@link JSpinner} y la
     * convierte a {@link LocalDateTime}.</li>
     * <li>Recupera la mascota seleccionada desde el {@link JComboBox} usando el
     * mapa {@code indexMascotas}.</li>
     * <li>Verifica qué servicios fueron seleccionados mediante los
     * {@link JCheckBox} correspondientes.</li>
     * <li>Valida que todos los campos obligatorios estén completos. Si falta
     * algún dato, muestra un mensaje de advertencia.</li>
     * <li>Recupera los servicios seleccionados desde la base de datos.</li>
     * <li>Crea un objeto {@link Cita} con los datos ingresados y lo guarda en
     * la base de datos mediante el controlador {@code control}.</li>
     * <li>Muestra un mensaje de confirmación de guardado y actualiza la tabla
     * de citas llamando a {@link #cargarTabla()}.</li>
     * <li>Limpia los campos del formulario utilizando
     * {@code FormUtils.limpiarFormulario(rootPane)}.</li>
     * </ul>
     *
     * @see Cita
     * @see Mascotas
     * @see Servicios
     * @see FormUtils#limpiarFormulario(java.awt.Container)
     */
    private void guardarCitas() {
        // Obtener la fecha directamente del JSpinner
        Date fechaSeleccionada = (Date) jsFecha.getValue();

        // Convertir a LocalDateTime para JPA
        LocalDateTime fechaHora = fechaSeleccionada.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDateTime();

        // Recuperar la mascota seleccionada usando el mapa indexMascotas
        String nombre = (String) cmbMascota1.getSelectedItem();
        Mascotas mascota = indexMascotas.get(nombre);

        boolean banio = jBoxBanio.isSelected();
        boolean corte = jBoxCorte.isSelected();
        boolean unias = jBoxUnias.isSelected();

        // Validar campos vacíos
        if (mascota == null || (!banio && !corte && !unias)) {
            JLabel label = new JLabel("Por favor, completa todos los campos antes de guardar.");
            label.setFont(new Font("Arial", Font.BOLD, 14));
            JOptionPane optionPane = new JOptionPane(label, JOptionPane.WARNING_MESSAGE, JOptionPane.DEFAULT_OPTION);
            JDialog dialog = optionPane.createDialog("Campos incompletos");
            dialog.setAlwaysOnTop(true);
            dialog.setVisible(true);
            return;
        }

        // Recoger servicios seleccionados desde la BD
        List<Servicios> serviciosSeleccionados = new ArrayList<>();

        if (banio) {
            Servicios sBanio = controlPersis.buscarServicioPorNombre("Baño");
            if (sBanio != null) {
                serviciosSeleccionados.add(sBanio);
            }
        }
        if (corte) {
            Servicios sCorte = controlPersis.buscarServicioPorNombre("Corte de pelo");
            if (sCorte != null) {
                serviciosSeleccionados.add(sCorte);
            }
        }
        if (unias) {
            Servicios sUnias = controlPersis.buscarServicioPorNombre("Corte de uñas");
            if (sUnias != null) {
                serviciosSeleccionados.add(sUnias);
            }
        }

        // Crear la cita
        Cita cita = new Cita();
        cita.setFechaHora(fechaHora);
        cita.setMascota(mascota);
        cita.setServicio(serviciosSeleccionados);

        // Guardar la cita en BD
        control.guardarCita(mascota.getNum_cliente(), fechaHora, serviciosSeleccionados);

        JLabel label = new JLabel("Se guardó correctamente");
        label.setFont(new Font("Arial", Font.BOLD, 14));
        JOptionPane optionPane = new JOptionPane(label, JOptionPane.INFORMATION_MESSAGE, JOptionPane.DEFAULT_OPTION);
        JDialog dialog = optionPane.createDialog("Guardado");
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);

        cargarTabla();
        FormUtils.limpiarFormulario(rootPane);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerTodo;
    private javax.swing.JComboBox<String> cmbMascota1;
    private javax.swing.JCheckBox jBoxBanio;
    private javax.swing.JCheckBox jBoxCorte;
    private javax.swing.JCheckBox jBoxUnias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jsFecha;
    private javax.swing.JTable tblCitas;
    // End of variables declaration//GEN-END:variables
}
