package igu;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import logica.Controladora;
import logica.FormUtils;
import logica.Usuarios;

/**
 * Ventana principal de inicio de sesión del sistema de peluquería canina.
 *
 * Esta clase extiende {@link javax.swing.JFrame} y proporciona la interfaz
 * gráfica para que el usuario introduzca sus credenciales. Incluye
 * comportamiento interactivo para el campo de texto del email, como sugerencias
 * y cambio de color.
 *
 * También establece la conexión con la base de datos al inicializarse.
 *
 * @author Alicia
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Referencia estática al formulario de registro, utilizada para invocar
     * desde otras ventanas.
     */
    public static FrmRegistro fr;

    Controladora control = null;

    /**
     * Constructor que inicializa la ventana de inicio de sesión.
     *
     * Configura la posición centrada, el ícono de la aplicación y el
     * comportamiento del campo de texto para el email con sugerencias visuales.
     */
    public FrmLogin() {
        initComponents();
        control = new Controladora();
        setLocationRelativeTo(null);
        Image icon = new ImageIcon("./icon/logo2.png").getImage();
        this.setIconImage(icon);

        FormUtils.habilitarAyuda(jmAyuda, getRootPane(), "aplicacion");

        txtUsuario.setText("Introduce email");
        txtUsuario.setForeground(Color.GRAY); // color de texto sugerido

        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (txtUsuario.getText().equals("Introduce email")) {
                    txtUsuario.setText("");
                    txtUsuario.setForeground(Color.BLACK); // color normal
                }
            }
        });
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtUsuario.getText().isEmpty()) {
                    txtUsuario.setText("Introduce email");
                    txtUsuario.setForeground(Color.GRAY);
                }
            }
        });
        getRootPane().setDefaultButton(btnIniciarSesion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jtPass = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\imgLogin.png")); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("User:");

        jLabel3.setText("Password:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario)
                    .addComponent(jtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnIniciarSesion.setText("Iniciar sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnRegistro.setText("Registrarse");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistro))
                        .addGap(49, 49, 49))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnRegistro)
                .addGap(1, 1, 1)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIniciarSesion)
                .addGap(22, 22, 22))
        );

        jMenu1.setText("Ayuda");

        jmAyuda.setText("Ayuda");
        jMenu1.add(jmAyuda);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción que se ejecuta al presionar el botón de "Registro".
     * <p>
     * Este método cierra la ventana actual y abre el formulario de registro de
     * usuarios como un diálogo modal. El formulario de registro se muestra
     * bloqueando la ventana padre hasta que se cierre.
     * </p>
     *
     * @param evt el evento generado al hacer clic en el botón
     */
    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        FormUtils.cambiarVentana(this, new FrmRegistro());
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        iniciarSesion();
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * Realiza el proceso de inicio de sesión de un usuario.
     * <p>
     * Este método obtiene el correo electrónico y la contraseña ingresados en
     * los campos de texto correspondientes, valida las credenciales mediante el
     * objeto de control y, si el usuario es válido, muestra un mensaje de
     * bienvenida y abre la ventana correspondiente según el rol del usuario.
     * Los roles soportados son:
     * </p>
     * <ul>
     * <li>ADMINISTRADOR: abre la ventana {@link Principal}</li>
     * <li>RECEPCIONISTA: abre la ventana {@link InicioRecepc}</li>
     * <li>TRABAJADOR: abre la ventana {@link PanelRecepcTrab}</li>
     * </ul>
     * <p>
     * Si el usuario no existe o las credenciales son incorrectas, se muestra un
     * mensaje de error indicando que las credenciales no son válidas. Si el rol
     * no está reconocido, se muestra un mensaje informando de ello.
     * </p>
     * <p>
     * Este método está diseñado para ser llamado tanto desde el evento de
     * acción del botón de inicio de sesión como desde la pulsación de la tecla
     * Enter.
     * </p>
     */
    private void iniciarSesion() {
        String email = txtUsuario.getText();
        String pass = jtPass.getText();

        Usuarios usuario = control.iniciarSesion(email, pass);

        if (usuario != null) {
            FormUtils.mostrarMensaje("Bienvenido " + usuario.getNombre() + " (" + usuario.getTipo_rol().getNombre() + ")", "Info", "Bienvenido");
            // Abrir ventana según rol
            String rol = usuario.getTipo_rol().getNombre().toUpperCase();
            switch (rol) {
                case "ADMINISTRADOR":
                    dispose();
                    Principal princ = new Principal();
                    princ.setVisible(true);
                    princ.setLocationRelativeTo(null);
                    break;
                case "RECEPCIONISTA":
                    dispose();
                    new InicioRecepc().setVisible(true);
                    break;
                case "TRABAJADOR":
                    dispose();
                    new PanelRecepcTrab("Trabajador").setVisible(true);
                    break;
                default:
                    FormUtils.mostrarMensaje("Rol no reconocido.", "Error", "Error en el rol");
            }
        } else {
            FormUtils.mostrarMensaje("Credenciales incorrectas. " + email + " Intenta de nuevo.", "Error", "Error al iniciar sesión");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem jmAyuda;
    private javax.swing.JPasswordField jtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
