package igu;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logica.FormUtils;

/**
 * Ventana principal del perfil "Recepcionista" en el sistema de gestión de
 * peluquería canina.
 *
 * Esta clase extiende {@link javax.swing.JFrame} y proporciona acceso a las
 * funcionalidades específicas para recepcionistas, como registro de mascotas,
 * gestión de citas o visualización de datos.
 *
 * Al inicializarse, configura los componentes gráficos, centra la ventana en
 * pantalla y establece el ícono personalizado de la aplicación.
 *
 * @author Alicia
 */
public class InicioRecepc extends javax.swing.JFrame {

    /**
     * Constructor que inicializa la interfaz gráfica del recepcionista.
     *
     * Configura los componentes visuales, establece el ícono de la ventana y
     * posiciona la interfaz en el centro de la pantalla.
     */
    public InicioRecepc() {
        initComponents();
        this.setLocationRelativeTo(null);
        Image icon = new ImageIcon("./icon/logo2.png").getImage();
        this.setIconImage(icon);

        FormUtils.habilitarAyuda(jmAyuda, getRootPane(), "aplicacion");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnVer = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        btnCita = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmCarga = new javax.swing.JMenuItem();
        jmVer = new javax.swing.JMenuItem();
        jmCitas = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenuItem();
        Ayuda = new javax.swing.JMenu();
        jmAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zona Recepcionista");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnVer.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        btnVer.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\usuario.png")); // NOI18N
        btnVer.setText("Ver Datos");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\salir.png")); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnCargar.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btnCargar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\guardar.png")); // NOI18N
        btnCargar.setText("Cargar Datos");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        btnCita.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btnCita.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\cita.png")); // NOI18N
        btnCita.setText("Citas");
        btnCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCita, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        jLabel1.setText("Peluquería Canina");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\logo2.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\menu-removebg-preview.png")); // NOI18N
        jMenu1.setText("Menu");

        jmCarga.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\guardar.png")); // NOI18N
        jmCarga.setText("Cargar Datos");
        jmCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCargaActionPerformed(evt);
            }
        });
        jMenu1.add(jmCarga);

        jmVer.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\usuario.png")); // NOI18N
        jmVer.setText("Ver Datos");
        jmVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmVerActionPerformed(evt);
            }
        });
        jMenu1.add(jmVer);

        jmCitas.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\cita.png")); // NOI18N
        jmCitas.setText("Citas");
        jmCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCitasActionPerformed(evt);
            }
        });
        jMenu1.add(jmCitas);

        jmSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\salir.png")); // NOI18N
        jmSalir.setText("Salir");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jmSalir);

        jMenuBar1.add(jMenu1);

        Ayuda.setText("Ayuda");

        jmAyuda.setText("Mostrar Ayuda");
        Ayuda.add(jmAyuda);

        jMenuBar1.add(Ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción ejecutada al hacer clic en el botón "Ver".
     *
     * Este método cierra la ventana actual y abre la interfaz
     * {@code PanelRecepc}, que permite al recepcionista visualizar los datos
     * registrados en el sistema. La nueva ventana se centra en la pantalla.
     *
     * @param evt Evento de acción generado por el botón.
     */
    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
       FormUtils.cambiarVentana(this, new PanelRecepcTrab("Recepcionista"));
    }//GEN-LAST:event_btnVerActionPerformed

    /**
     * Acción ejecutada al hacer clic en el botón "Salir".
     *
     * Este método cierra la ventana actual y redirige al formulario de inicio
     * de sesión {@code FrmLogin}, permitiendo al usuario cerrar sesión o
     * cambiar de perfil.
     *
     * @param evt Evento de acción generado por el botón.
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //Botón Salir
        int resultado = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de cerrar sesión?",
                "Atención", JOptionPane.YES_OPTION);

        if (resultado == JOptionPane.YES_OPTION) {
            FormUtils.cambiarVentana(this, new FrmLogin());
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * Acción realizada al presionar el botón "Cargar".
     * <p>
     * Este método cierra la ventana actual y abre la ventana
     * {@link CargarDatos} configurada para el rol de "Recepcionista". Además,
     * centra la nueva ventana en la pantalla y la hace visible.
     *
     * @param evt el evento de acción generado al pulsar el botón
     * @see CargarDatos
     */
    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        FormUtils.cambiarVentana(this, new CargarDatos("Recepcionista"));
    }//GEN-LAST:event_btnCargarActionPerformed

    /**
     *
     * @param evt
     */
    private void jmVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmVerActionPerformed
        FormUtils.cambiarVentana(this, new PanelRecepcTrab("Recepcionista"));
    }//GEN-LAST:event_jmVerActionPerformed

    /**
     *
     * @param evt
     */
    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        FormUtils.cambiarVentana(this, new FrmLogin());
    }//GEN-LAST:event_jmSalirActionPerformed

    /**
     * Acción realizada al seleccionar el menú "Cargar" (jmCarga).
     * <p>
     * Este método cierra la ventana actual y abre la ventana
     * {@link CargarDatos} configurada para el rol de "Recepcionista". La nueva
     * ventana se centra en la pantalla y se hace visible al usuario.
     *
     * @param evt el evento de acción generado al seleccionar el ítem del menú
     * @see CargarDatos
     */
    private void jmCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCargaActionPerformed
        FormUtils.cambiarVentana(this, new CargarDatos("Recepcionista"));
    }//GEN-LAST:event_jmCargaActionPerformed

    private void btnCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitaActionPerformed
        FormUtils.cambiarVentana(this, new FrmCitas("Recepcionista"));
    }//GEN-LAST:event_btnCitaActionPerformed

    /**
     * Acción realizada al seleccionar el menú "Citas" (jmCitas).
     * <p>
     * Este método cierra la ventana actual y abre la ventana {@link FrmCitas}
     * configurada para el rol de "Recepcionista". La nueva ventana se centra en
     * la pantalla y se hace visible al usuario.
     *
     * @param evt el evento de acción generado al seleccionar el ítem del menú
     * @see FrmCitas
     */
    private void jmCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCitasActionPerformed
        FormUtils.cambiarVentana(this, new FrmCitas("Recepcionista"));
    }//GEN-LAST:event_jmCitasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ayuda;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnCita;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem jmAyuda;
    private javax.swing.JMenuItem jmCarga;
    private javax.swing.JMenuItem jmCitas;
    private javax.swing.JMenuItem jmSalir;
    private javax.swing.JMenuItem jmVer;
    // End of variables declaration//GEN-END:variables
}
