package igu;

import java.awt.Image;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import logica.Controladora;
import logica.FormUtils;
import logica.Mascotas;
import logica.Servicios; 
import persistencia.MascotasJpaController;

/**
 * Panel principal del perfil "Recepcionista" en el sistema de gestión de
 * peluquería canina.
 *
 * Esta clase extiende {@link javax.swing.JFrame} y proporciona acceso a las
 * funcionalidades específicas para recepcionistas, como la visualización,
 * edición y eliminación de datos de mascotas y sus dueños.
 *
 * Al inicializarse, se configura la interfaz gráfica, se establece el ícono de
 * la aplicación y se crea una instancia de {@link Controladora} para gestionar
 * la lógica de negocio.
 *
 */
public class PanelRecepcTrab extends javax.swing.JFrame {

    /**
     * Instancia de la clase Controladora para acceder a la lógica de negocio.
     */
    private Controladora control;
    private String rolActual;

    /**
     * Constructor que inicializa el panel de trabajo del recepcionista.
     *
     * Configura los componentes gráficos, establece el ícono de la ventana y
     * prepara la interfaz para la interacción del usuario.
     */
    public PanelRecepcTrab(String rol) {
        control = new Controladora();
        initComponents();
        Image icon = new ImageIcon("./icon/logo2.png").getImage();
        this.setIconImage(icon);
        this.rolActual = rol;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMascota = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zona Recepcionista-Trabajador");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("AliCan");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaMascota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaMascota);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 2, 14)); // NOI18N
        jLabel2.setText("Datos Mascotas:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(552, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnCerrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\salir.png")); // NOI18N
        btnCerrar.setToolTipText("Atrás");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\buscar1.png")); // NOI18N
        btnBuscar.setToolTipText("Buscar dueño");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\canino.png")); // NOI18N
        jButton1.setToolTipText("Ver todo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnCerrar))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param evt
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarTabla();
    }//GEN-LAST:event_formWindowOpened
 
    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        FormUtils.salirSegunRol(rolActual, this);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarDuenio();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cargarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Carga y muestra en la tabla todos los registros de mascotas almacenados
     * en la base de datos.
     *
     * Este método crea un modelo de tabla no editable, define los encabezados
     * de columna y obtiene la lista de mascotas desde la capa de control
     * mediante {@code control.traerMascotas()}.
     *
     * Por cada mascota encontrada, se crea una fila con los siguientes datos:
     * número de cliente, nombre, raza, color, si es alérgico, si requiere
     * atención especial, nombre del dueño, teléfono del dueño y observaciones.
     *
     * Finalmente, el modelo generado se asigna al componente
     * {@code tablaMascota}.
     */
    public void cargarTabla() {

        // definir modelo de la tabla
        DefaultTableModel modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // no editable desde la interfaz
            }
        };

        // establecemos los nombres de la columna (añadimos Servicios)
        String titulos[] = {"Id", "Nombre", "Raza", "Color", "Alergico", "At. Esp.", "Dueño", "Tlf", "Observ.", "Servicios"};
        modeloTabla.setColumnIdentifiers(titulos);

        // carga de los datos desde la BD
        List<Mascotas> listaMascota = control.traerMascotas();

        // recorrer la lista y mostrar cada uno de los elementos en la tabla
        if (listaMascota != null) {
            for (Mascotas masco : listaMascota) {

                // Construir texto con los servicios
                String serviciosTexto = "Sin servicios";
                if (masco.getServicios() != null && !masco.getServicios().isEmpty()) {
                    StringBuilder sb = new StringBuilder();
                    for (Servicios s : masco.getServicios()) {
                        sb.append(s.getTipoServicios())
                                .append(" (")
                                .append(s.getPrecio())
                                .append("€), ");
                    }
                    // quitar la última coma y espacio
                    serviciosTexto = sb.substring(0, sb.length() - 2);
                }

                Object[] objeto = {
                    masco.getNum_cliente(),
                    masco.getNombreMas(),
                    masco.getRaza(),
                    masco.getColor(),
                    masco.getAlergico(),
                    masco.getAtencion_especial(),
                    masco.getUnDuenio().getNombre(),
                    masco.getUnDuenio().getTelefono(),
                    masco.getObservaciones(),
                    serviciosTexto 
                };

                modeloTabla.addRow(objeto);
            }
            tablaMascota.setModel(modeloTabla);  // asignar modelo a la tabla
      
            // Ajustes de ancho de columnas
            TableColumnModel columnModel = tablaMascota.getColumnModel();

            columnModel.getColumn(0).setPreferredWidth(30);
            columnModel.getColumn(0).setMinWidth(30);
            columnModel.getColumn(0).setMaxWidth(30);
            
            columnModel.getColumn(1).setPreferredWidth(80);
            columnModel.getColumn(2).setPreferredWidth(80);
            columnModel.getColumn(3).setPreferredWidth(70);
            columnModel.getColumn(4).setPreferredWidth(40);

            columnModel.getColumn(5).setPreferredWidth(40);
            
            columnModel.getColumn(6).setPreferredWidth(80);
            columnModel.getColumn(7).setPreferredWidth(80);

            columnModel.getColumn(8).setPreferredWidth(150);
            columnModel.getColumn(9).setMinWidth(150);
        }
    }

    /**
     * Acción ejecutada al hacer clic en el botón "Buscar".
     *
     * Este método solicita al usuario que introduzca el nombre de un dueño
     * mediante un cuadro de diálogo. Si se proporciona un nombre válido, se
     * consulta la base de datos a través de {@code MascotasJpaController} para
     * obtener todas las mascotas asociadas a ese dueño.
     *
     * La tabla de mascotas se limpia antes de mostrar los nuevos resultados. Si
     * no se encuentran coincidencias, se muestra un mensaje informativo. Si no
     * se introduce ningún nombre, se muestra una advertencia al usuario.
     *
     */
    private void buscarDuenio() {                                          
        String nombreBuscado = JOptionPane.showInputDialog(this, "Introduce el nombre del dueño:");

        if (nombreBuscado != null && !nombreBuscado.trim().isEmpty()) {
            MascotasJpaController controlMascota = new MascotasJpaController();
            List<Mascotas> lista = controlMascota.findMascotasByNombreDueno(nombreBuscado.trim());
            DefaultTableModel modelo = (DefaultTableModel) tablaMascota.getModel();

            modelo.setRowCount(0); // Limpiar tabla

            if (lista.isEmpty()) { 
                 FormUtils.mostrarMensaje("No se encontraron mascotas para ese dueño: " + nombreBuscado, "Error", "Dueño no encontrado"); 
            } else {
                for (Mascotas m : lista) {
                    // Construir un string con todos los servicios de la mascota
                    String serviciosTexto = "";
                    if (m.getServicios() != null && !m.getServicios().isEmpty()) {
                        StringBuilder sb = new StringBuilder();
                        for (Servicios s : m.getServicios()) {
                            sb.append(s.getTipoServicios())
                                    .append(" (")
                                    .append(s.getPrecio())
                                    .append("€), ");
                        }
                        // Quitar la última coma y espacio
                        serviciosTexto = sb.substring(0, sb.length() - 2);
                    } else {
                        serviciosTexto = "Sin servicios";
                    }

                    // Añadir fila a la tabla incluyendo los servicios
                    modelo.addRow(new Object[]{
                        m.getNum_cliente(),
                        m.getNombreMas(),
                        m.getRaza(),
                        m.getColor(),
                        m.getAlergico(),
                        m.getAtencion_especial(),
                        m.getUnDuenio().getNombre(),
                        m.getUnDuenio().getTelefono(),
                        m.getObservaciones(),
                        serviciosTexto 
                    });
                }
            }
        } else {
             FormUtils.mostrarMensaje("No se introdujo ningún nombre.", "Error", "Dueño no encontrado"); 
         }
       
    }     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaMascota;
    // End of variables declaration//GEN-END:variables
}
