package igu;

import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import logica.Controladora;
import logica.FormUtils;
import logica.Mascotas;
import logica.Servicios;
import persistencia.MascotasJpaController;

/**
 * Ventana de visualización de datos en el sistema de gestión de peluquería
 * canina.
 *
 * Esta clase extiende {@link javax.swing.JFrame} y permite al usuario consultar
 * los registros de mascotas y sus respectivos dueños. Es utilizada por perfiles
 * como recepcionistas o trabajadores para acceder a la información almacenada.
 *
 * Al inicializarse, se configura la interfaz gráfica, se establece el ícono de
 * la aplicación y se crea una instancia de {@link Controladora} para acceder a
 * la lógica de negocio.
 *
 */
public class VerDatos extends javax.swing.JFrame {

    /**
     * Instancia de la clase Controladora para acceder a la lógica de negocio.
     */
    Controladora control = null;

    /**
     * Constructor que inicializa la ventana de visualización de datos.
     *
     * Configura los componentes gráficos, establece el ícono de la ventana y
     * prepara la interfaz para mostrar registros.
     */
    public VerDatos() {
        control = new Controladora();
        initComponents();
        Image icon = new ImageIcon("./icon/logo2.png").getImage();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMascota = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        verTodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AliCan Administrador");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel1.setText("Datos");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaMascota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaMascota);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 2, 14)); // NOI18N
        jLabel2.setText("Datos Mascotas:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\editar.png")); // NOI18N
        btnEditar.setToolTipText("Modificar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\eliminar.png")); // NOI18N
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalir1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\salir.png")); // NOI18N
        btnSalir1.setToolTipText("Volver");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\buscar1.png")); // NOI18N
        btnBuscar.setToolTipText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        verTodo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\canino.png")); // NOI18N
        verTodo.setToolTipText("Ver todo");
        verTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(verTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                    .addComponent(verTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarDuenio();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarTabla();
    }//GEN-LAST:event_formWindowOpened

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarMasco();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        editarMasco();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        FormUtils.cambiarVentana(this, new Principal());
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void verTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTodoActionPerformed
        cargarTabla();
    }//GEN-LAST:event_verTodoActionPerformed

    /**
     * Acción ejecutada al hacer clic en el botón "Buscar".
     *
     * Este método solicita al usuario que introduzca el nombre de un dueño
     * mediante un cuadro de diálogo. Si se proporciona un nombre válido, se
     * consulta la base de datos a través de {@code MascotasJpaController} para
     * obtener todas las mascotas asociadas a ese dueño.
     *
     * La tabla de mascotas se limpia antes de mostrar los nuevos resultados. Si
     * no se encuentran coincidencias, se muestra un mensaje informativo. Si no
     * se introduce ningún nombre, se muestra una advertencia al usuario.
     *
     */
    private void buscarDuenio() {

        String nombreBuscado = JOptionPane.showInputDialog(this, "Introduce el nombre del dueño:");

        if (nombreBuscado != null && !nombreBuscado.trim().isEmpty()) {
            MascotasJpaController controlMascota = new MascotasJpaController();
            List<Mascotas> lista = controlMascota.findMascotasByNombreDueno(nombreBuscado.trim());
            DefaultTableModel modelo = (DefaultTableModel) tablaMascota.getModel();

            modelo.setRowCount(0); // Limpiar tabla

            if (lista.isEmpty()) {
                FormUtils.mostrarMensaje("No se encontraron mascotas para ese dueño: " + nombreBuscado, "Error", "Error en la búsqueda");
            } else {
                for (Mascotas m : lista) {
                    // Construir un string con todos los servicios de la mascota
                    String serviciosTexto = "";
                    if (m.getServicios() != null && !m.getServicios().isEmpty()) {
                        StringBuilder sb = new StringBuilder();
                        for (Servicios s : m.getServicios()) {
                            sb.append(s.getTipoServicios())
                                    .append(" (")
                                    .append(s.getPrecio())
                                    .append("€), ");
                        }
                        // Quitar la última coma y espacio
                        serviciosTexto = sb.substring(0, sb.length() - 2);
                    } else {
                        serviciosTexto = "Sin servicios";
                    }

                    // Añadir fila a la tabla incluyendo los servicios
                    modelo.addRow(new Object[]{
                        m.getNum_cliente(),
                        m.getNombreMas(),
                        m.getRaza(),
                        m.getColor(),
                        m.getAlergico(),
                        m.getAtencion_especial(),
                        m.getUnDuenio().getNombre(),
                        m.getUnDuenio().getTelefono(),
                        m.getObservaciones(),
                        serviciosTexto // ✅ nueva columna con servicios
                    });
                }
            }
        } else {
            FormUtils.mostrarMensaje("No se introdujo ningún nombre.", "Error", "Error en la búsqueda");
        }
    }

    /**
     * Acción ejecutada al hacer clic en el botón "Eliminar".
     *
     * Este método verifica si hay filas en la tabla de mascotas y si alguna
     * está seleccionada. Si se selecciona una fila, solicita confirmación al
     * usuario para eliminar la mascota correspondiente. Si el usuario confirma,
     * se llama al método {@code borrarMascota()} de la clase
     * {@code Controladora} para eliminarla de la base de datos.
     *
     * Luego se muestra un mensaje informativo y se actualiza la tabla. Si no
     * hay selección o la tabla está vacía, se muestran mensajes de error
     * apropiados.
     */
    private void eliminarMasco() {
        // si hay linea
        if (tablaMascota.getRowCount() > 0) {
            int filaSeleccionada = tablaMascota.getSelectedRow();
            if (filaSeleccionada != -1) {
                // Obtener nombre de la mascota si está en la columna 1 (ajusta si es otra)
                String nombreMascota = String.valueOf(tablaMascota.getValueAt(filaSeleccionada, 1));
                int num_cliente = Integer.parseInt(String.valueOf(tablaMascota.getValueAt(filaSeleccionada, 0)));

                int confirmacion = JOptionPane.showConfirmDialog(this,
                        "¿Estás segura de eliminar a la mascota \"" + nombreMascota + "\"?\nSe perderán sus datos.",
                        "Confirmar eliminación",
                        JOptionPane.YES_NO_OPTION);

                if (confirmacion == JOptionPane.YES_OPTION) {
                    control.borrarMascota(num_cliente);
                    FormUtils.mostrarMensaje("Mascota eliminada correctamente", "Info", "Borrado Mascota");
                    cargarTabla();
                }
            } else {
                FormUtils.mostrarMensaje("No se seleccionó ninguna mascota", "Error", "Error al eliminar");
            }
        } else {
            FormUtils.mostrarMensaje("No hay nada para eliminar en la tabla", "Error", "Error al eliminar");
        }

    }

    /**
     * Acción ejecutada al hacer clic en el botón "Editar".
     *
     * Este método verifica si hay filas en la tabla de mascotas y si alguna
     * está seleccionada. Si se selecciona una fila, obtiene el número de
     * cliente de la mascota y abre la ventana {@code ModificarDatos} para
     * editar sus datos. La ventana actual se cierra.
     *
     * Si no hay selección o la tabla está vacía, se muestran mensajes de error
     * apropiados.
     */
    private void editarMasco() {
        // si hay linea
        if (tablaMascota.getRowCount() > 0) {
            // si el resultado es -1 no hay nada seleccionado
            if (tablaMascota.getSelectedRow() != -1) {
                //obtengo la id de la mascota a editar
                int num_cliente = Integer.parseInt(String.valueOf(tablaMascota.getValueAt(tablaMascota.getSelectedRow(), 0)));

                FormUtils.cambiarVentana(this, new ModificarDatos(num_cliente));
       
            } else {
                FormUtils.mostrarMensaje("No se seleccionó ninguna mascota", "Error", "Error al eliminar");
            }
        } else {
            FormUtils.mostrarMensaje("No hay nada para eliminar en la table", "Error", "Error al eliminar");
        }
    }

    /**
     * Carga los datos de todas las mascotas registradas en la base de datos y
     * los muestra en la tabla de la interfaz gráfica.
     *
     * Este método define un modelo de tabla no editable, establece los
     * encabezados de columna y recorre la lista de mascotas obtenida desde la
     * capa de control.
     *
     * Cada mascota se representa como una fila con sus atributos y los de su
     * dueño, incluyendo número de cliente, nombre, raza, color, alergias,
     * atención especial, nombre del dueño, teléfono y observaciones.
     *
     * Si la lista de mascotas no es nula, se actualiza el componente
     * {@code tablaMascota} con el modelo generado.
     */
    public void cargarTabla() {

        // definir modelo de la tabla
        DefaultTableModel modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // no editable desde la interfaz
            }
        };

        // establecemos los nombres de la columna (añadimos Servicios)
        String titulos[] = {"Id", "Nombre", "Raza", "Color", "Alergico", "At. Esp.", "Dueño", "Tlf", "Observ.", "Servicios"};
        modeloTabla.setColumnIdentifiers(titulos);

        // carga de los datos desde la BD
        List<Mascotas> listaMascota = control.traerMascotas();

        // recorrer la lista y mostrar cada uno de los elementos en la tabla
        if (listaMascota != null) {
            for (Mascotas masco : listaMascota) {

                // Construir texto con los servicios
                String serviciosTexto = "Sin servicios";
                if (masco.getServicios() != null && !masco.getServicios().isEmpty()) {
                    StringBuilder sb = new StringBuilder();
                    for (Servicios s : masco.getServicios()) {
                        sb.append(s.getTipoServicios())
                                .append(" (")
                                .append(s.getPrecio())
                                .append("€), ");
                    }
                    // quitar la última coma y espacio
                    serviciosTexto = sb.substring(0, sb.length() - 2);
                }

                Object[] objeto = {
                    masco.getNum_cliente(),
                    masco.getNombreMas(),
                    masco.getRaza(),
                    masco.getColor(),
                    masco.getAlergico(),
                    masco.getAtencion_especial(),
                    masco.getUnDuenio().getNombre(),
                    masco.getUnDuenio().getTelefono(),
                    masco.getObservaciones(),
                    serviciosTexto
                };

                modeloTabla.addRow(objeto);
            }
            tablaMascota.setModel(modeloTabla);  // asignar modelo a la tabla

            // Ajustes de ancho de columnas
            TableColumnModel columnModel = tablaMascota.getColumnModel();

            columnModel.getColumn(0).setPreferredWidth(30);
            columnModel.getColumn(0).setMinWidth(30);
            columnModel.getColumn(0).setMaxWidth(30);

            columnModel.getColumn(1).setPreferredWidth(80);
            columnModel.getColumn(2).setPreferredWidth(100);
            columnModel.getColumn(3).setPreferredWidth(70);
            columnModel.getColumn(4).setPreferredWidth(40);

            columnModel.getColumn(5).setPreferredWidth(40);

            columnModel.getColumn(6).setPreferredWidth(80);
            columnModel.getColumn(7).setPreferredWidth(80);

            columnModel.getColumn(8).setPreferredWidth(150);
            columnModel.getColumn(9).setMinWidth(150);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMascota;
    private javax.swing.JButton verTodo;
    // End of variables declaration//GEN-END:variables

}
