package igu;

import controlador.ControlMascotas;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.FormUtils;
import logica.Mascotas;

/**
 * Ventana de visualización de datos en el sistema de gestión de peluquería
 * canina.
 *
 * Esta clase extiende {@link javax.swing.JFrame} y permite al usuario consultar
 * los registros de mascotas y sus respectivos dueños. Es utilizada por perfiles
 * como recepcionistas o trabajadores para acceder a la información almacenada.
 *
 * Al inicializarse, se configura la interfaz gráfica, se establece el ícono de
 * la aplicación y se crea una instancia de {@link Controladora} para acceder a
 * la lógica de negocio.
 *
 */
public class VerDatos extends javax.swing.JFrame {

    /**
     * Instancia de la clase Controladora para acceder a la lógica de negocio.
     */
    ControlMascotas controlMascotas = null;

    /**
     * Rol del usuario que abrió la ventana (Ej. "Recepcionista", "Trabajador").
     */
    private String rolActual;

    /**
     * Constructor que inicializa la ventana de visualización de datos.
     *
     * Configura los componentes gráficos, establece el ícono de la ventana y
     * prepara la interfaz para mostrar registros.
     *
     * @param rolActual
     */
    public VerDatos(String rolActual) {
        initComponents();
        Image icon = new ImageIcon("./icon/logo2.png").getImage();
        this.setIconImage(icon);
        this.rolActual = rolActual.trim().toLowerCase();
        this.controlMascotas = new ControlMascotas();
        DefaultTableModel modelo = new DefaultTableModel(
                new String[]{
                    "Id", "Nombre", "Raza", "Color", "Alergico", "At. Esp.",
                    "Dueño", "Tlf", "Observ.", "Servicios"
                }, 0
        );
        tablaMascota.setModel(modelo);

        aplicarPermisos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMascota = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        verTodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AliCan Administrador");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel1.setText("Datos");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaMascota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaMascota);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 2, 14)); // NOI18N
        jLabel2.setText("Datos Mascotas:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\editar.png")); // NOI18N
        btnEditar.setToolTipText("Modificar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\eliminar.png")); // NOI18N
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalir1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\salir.png")); // NOI18N
        btnSalir1.setToolTipText("Volver");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\buscar1.png")); // NOI18N
        btnBuscar.setToolTipText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        verTodo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\canino.png")); // NOI18N
        verTodo.setToolTipText("Ver todo");
        verTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(verTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                    .addComponent(verTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarDuenio();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarTabla();
    }//GEN-LAST:event_formWindowOpened

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarMasco();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        editarMasco();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
       FormUtils.salirSegunRol(rolActual, this);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void verTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTodoActionPerformed
        cargarTabla();
    }//GEN-LAST:event_verTodoActionPerformed

    private void aplicarPermisos() {
        if (rolActual == null) {
            return;
        }

        String rol = rolActual.toLowerCase();

        if (rol.equals("recepcionista") || rol.equals("trabajador")) {
            btnEditar.setEnabled(false);
            btnEliminar.setEnabled(false);
        }
    }


    public void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tablaMascota.getModel();
        modelo.setRowCount(0);

        for (Object[] fila : controlMascotas.obtenerFilasTabla(controlMascotas.traerMascotas())) {
            modelo.addRow(fila);
        }
    }

    private void buscarDuenio() {
        String nombre = JOptionPane.showInputDialog(this, "Introduce el nombre del dueño:");

        if (nombre == null || nombre.trim().isEmpty()) {
            FormUtils.mostrarMensaje("No se introdujo ningún nombre.", "Error", "Búsqueda");
            return;
        }

        List<Mascotas> lista = controlMascotas.buscarPorNombreDuenio(nombre.trim());
        DefaultTableModel modelo = (DefaultTableModel) tablaMascota.getModel();
        modelo.setRowCount(0);

        if (lista.isEmpty()) {
            FormUtils.mostrarMensaje("No se encontraron mascotas para ese dueño.", "Info", "Sin resultados");
            return;
        }

        for (Object[] fila : controlMascotas.obtenerFilasTabla(lista)) {
            modelo.addRow(fila);
        }
    }

    /**
     * Acción ejecutada al hacer clic en el botón "Eliminar".
     *
     * Este método verifica si hay filas en la tabla de mascotas y si alguna
     * está seleccionada. Si se selecciona una fila, solicita confirmación al
     * usuario para eliminar la mascota correspondiente. Si el usuario confirma,
     * se llama al método {@code borrarMascota()} de la clase
     * {@code Controladora} para eliminarla de la base de datos.
     *
     * Luego se muestra un mensaje informativo y se actualiza la tabla. Si no
     * hay selección o la tabla está vacía, se muestran mensajes de error
     * apropiados.
     */
    private void eliminarMasco() {
        if (tablaMascota.getSelectedRow() == -1) {
            FormUtils.mostrarMensaje("No se seleccionó ninguna mascota.", "Error", "Eliminar");
            return;
        }

        int num_cliente = (int) tablaMascota.getValueAt(tablaMascota.getSelectedRow(), 0);

        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Seguro que deseas eliminar esta mascota?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            controlMascotas.borrarMascota(num_cliente);
            cargarTabla();
            FormUtils.mostrarMensaje("Mascota eliminada correctamente.", "Info", "Eliminada");
        }
    }

    /**
     * Acción ejecutada al hacer clic en el botón "Editar".
     *
     * Este método verifica si hay filas en la tabla de mascotas y si alguna
     * está seleccionada. Si se selecciona una fila, obtiene el número de
     * cliente de la mascota y abre la ventana {@code ModificarDatos} para
     * editar sus datos. La ventana actual se cierra.
     *
     * Si no hay selección o la tabla está vacía, se muestran mensajes de error
     * apropiados.
     */
    private void editarMasco() {
        if (tablaMascota.getSelectedRow() == -1) {
            FormUtils.mostrarMensaje("No se seleccionó ninguna mascota", "Error", "Editar");
            return;
        }

        int num_cliente = (int) tablaMascota.getValueAt(tablaMascota.getSelectedRow(), 0);

        FormUtils.cambiarVentana(this, new ModificarDatos(num_cliente, rolActual));

    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMascota;
    private javax.swing.JButton verTodo;
    // End of variables declaration//GEN-END:variables

}
