package igu;

import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import logica.Controladora;
import logica.FormUtils;
import logica.InputKey;
import logica.Rol;
import logica.Usuarios;

/**
 * Ventana de visualización de usuarios en el sistema de gestión de peluquería
 * canina.
 *
 * <p>Esta clase extiende {@link javax.swing.JFrame} y permite consultar los
 * registros de usuarios almacenados en la base de datos. La ventana muestra
 * información relevante de los usuarios y facilita su gestión dentro del
 * sistema.</p>
 *
 * <p>Se apoya en la clase {@link Controladora} para acceder a la lógica de
 * negocio, realizar consultas y obtener los datos necesarios para la
 * visualización.</p>
 *
 * <p>Al inicializarse, configura los componentes gráficos, establece el ícono
 * de la aplicación y prepara las instancias necesarias para la interacción con
 * la capa lógica.</p>
 */
public class VerUsuarios extends javax.swing.JFrame {

    /**
     * Instancia de la clase Controladora para acceder a la lógica de negocio.
     */
    Controladora control = null;

    /**
     * Constructor que inicializa la ventana de visualización de usuarios.
     *
     * <p>Configura los componentes gráficos, establece el ícono de la ventana y
     * crea la instancia de {@link Controladora} necesaria para obtener los
     * datos que serán mostrados.</p>
     */
    public VerUsuarios() {
        control = new Controladora();
        initComponents();
        Image icon = new ImageIcon("./icon/logo2.png").getImage();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        btnModif = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnVerTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alician administrador");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\salir.png")); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setActionCommand("");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\eliminar.png")); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios"));

        tablaUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellidos", "Email", "Pass", "Tipo"
            }
        ));
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("Usuarios");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidosKeyPressed(evt);
            }
        });

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellidos:");

        jLabel6.setText("Email:");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Administrador", "Recepcionista", "Trabajador" }));
        comboTipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Usuario:"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnModif.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\editar.png")); // NOI18N
        btnModif.setText("Modificar");
        btnModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\buscar1.png")); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnVerTodos.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alicia\\Documents\\NetBeansProjects\\PeluqueriaCanina\\icon\\usuario.png")); // NOI18N
        btnVerTodos.setText("Ver Todos");
        btnVerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnModif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVerTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(333, 333, 333)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVerTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnBuscar)
                        .addGap(31, 31, 31)
                        .addComponent(btnEliminar)
                        .addGap(29, 29, 29)
                        .addComponent(btnModif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarTablaUsuarios();
    }//GEN-LAST:event_formWindowOpened

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        FormUtils.cambiarVentana(this, new Principal());
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarUsuario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * Acción ejecutada al hacer clic en una fila de la tabla de usuarios.
     *
     * Este método permite que, al seleccionar una fila de la tabla, los datos
     * del usuario correspondiente se carguen automáticamente en los campos de
     * texto del formulario para su visualización o edición.
     *
     * Si no se selecciona ninguna fila, se muestra un mensaje de advertencia.
     *
     * @param evt Evento de clic del mouse sobre la tabla.
     */
    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        //Al seleccionar en la tabla una fila se nos escriba en el campo de texto.

        int fila = tablaUsuarios.getSelectedRow();
        if (fila == -1) {
            FormUtils.mostrarMensaje("Usuario no seleccionado", "Error", "Seleccionar");
        } else {
            // int id = Integer.parseInt((String) tablaUsuarios.getValueAt(fila, 0).toString());
            String nom = (String) tablaUsuarios.getValueAt(fila, 1);
            String apellidos = (String) tablaUsuarios.getValueAt(fila, 2);
            String email = (String) tablaUsuarios.getValueAt(fila, 3);
            String tipo = (String) tablaUsuarios.getValueAt(fila, 4);

            txtNombre.setText(nom);
            txtApellidos.setText(apellidos);
            txtemail.setText(email);

            comboTipo.setSelectedItem(tipo);

        }
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void btnModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifActionPerformed
        modificar();
    }//GEN-LAST:event_btnModifActionPerformed


    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarPorRol();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTodosActionPerformed
        cargarTablaUsuarios();
    }//GEN-LAST:event_btnVerTodosActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        InputKey.soloLetras(evt);
        InputKey.limitar(evt, txtNombre, 20);
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtApellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyPressed
        InputKey.soloLetras(evt);
        InputKey.limitar(evt, txtApellidos, 20);
    }//GEN-LAST:event_txtApellidosKeyPressed

    /**
     * Carga y muestra los usuarios registrados en la tabla de la interfaz.
     * <p>
     * Este método obtiene la lista de usuarios desde la capa de control, crea
     * un modelo de tabla no editable, asigna los títulos de las columnas y
     * llena la tabla con los datos de cada usuario.
     * <p>
     * Además, ajusta el ancho de algunas columnas para una mejor visualización:
     * <ul>
     * <li>Columna Id: ancho pequeño</li>
     * <li>Columna Nombre: ancho medio</li>
     * </ul>
     */
    public void cargarTablaUsuarios() {
        DefaultTableModel modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        String titulos[] = {"Id", "Nombre", "Apellidos", "Email", "Rol"};
        modeloTabla.setColumnIdentifiers(titulos);

        List<Usuarios> listaUsuarios = control.traerUsuarios();

        if (listaUsuarios != null) {
            for (Usuarios u : listaUsuarios) {
                Object[] fila = {
                    u.getId(),
                    u.getNombre(),
                    u.getApellidos(),
                    u.getEmail(),
                    (u.getTipo_rol() != null ? u.getTipo_rol().getNombre() : "Sin rol")
                };
                modeloTabla.addRow(fila);
            }
            tablaUsuarios.setModel(modeloTabla);

            TableColumnModel columnModel = tablaUsuarios.getColumnModel();

            columnModel.getColumn(0).setPreferredWidth(30);
            columnModel.getColumn(0).setMinWidth(30);
            columnModel.getColumn(0).setMaxWidth(30);

            columnModel.getColumn(1).setPreferredWidth(50);

        }
    }

    /**
     * Acción ejecutada al hacer clic en el botón "Modificar".
     *
     * Este método recopila los datos del formulario, valida que no haya campos
     * vacíos y actualiza el registro del usuario en la base de datos mediante
     * el método {@code modificar()} de {@code modU}.
     *
     * Si la modificación es exitosa, se muestra un mensaje de confirmación, se
     * limpian los campos y se actualiza la tabla. En caso contrario, se muestra
     * un mensaje de error.
     *
     */
    private void modificar() {
        int fila = tablaUsuarios.getSelectedRow();
        if (fila != -1) {
            int idUsuario = (int) tablaUsuarios.getValueAt(fila, 0);
            Usuarios usuario = control.traerUsuario(idUsuario);

            String nuevoNombre = txtNombre.getText().trim();
            String nuevoApellidos = txtApellidos.getText().trim();
            String nuevoEmail = txtemail.getText().trim();

            // Validar que no haya campos vacíos
            if (nuevoNombre.isEmpty() || nuevoApellidos.isEmpty() || nuevoEmail.isEmpty()) {
                FormUtils.mostrarMensaje("Debe completar todos los campos.", "Error", "Completar campos.");
                return;
            }

            // Validar formato de email
            String patronEmail = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$";
            if (!nuevoEmail.matches(patronEmail)) {
                FormUtils.mostrarMensaje("El correo electrónico no tiene un formato válido.", "Error", "Error al guardar");

                return;
            }

            // Validar que el email no esté duplicado en otro usuario
            boolean existeEmail = false;
            for (Usuarios u : control.traerUsuarios()) {
                if (u.getEmail().equalsIgnoreCase(nuevoEmail) && u.getId() != idUsuario) {
                    existeEmail = true;
                    break;
                }
            }

            if (existeEmail) {
                FormUtils.mostrarMensaje("El correo " + nuevoEmail + " ya está registrado en otro usuario.", "Error", "Correo registrado.");
                FormUtils.limpiarFormulario(rootPane);
                return;
            }

            //  Actualizar con los valores de los campos
            usuario.setNombre(nuevoNombre);
            usuario.setApellidos(nuevoApellidos);
            usuario.setEmail(nuevoEmail);

            //  Buscar rol en BD
            Rol rol = null;
            for (Rol r : control.traerRoles()) {
                if (r.getNombre().equalsIgnoreCase(comboTipo.getSelectedItem().toString())) {
                    rol = r;
                    break;
                }
            }
            if (rol != null) {
                usuario.setTipo_rol(rol);
            }

            //  Guardar cambios
            try {
                control.modificarUsuario(usuario);
                cargarTablaUsuarios();
                FormUtils.mostrarMensaje("Usuario modificado correctamente.", "Info", "Usuario modificado");

            } catch (Exception ex) {
                FormUtils.mostrarMensaje("Error al modificar el usuario: " + ex.getMessage(), "Error", "Error");
            }
        } else {
            FormUtils.mostrarMensaje("Selecciona un usuario para modificar.", "Error", "Usuario");
        }
    }

    /**
     * Acción ejecutada al hacer clic en el botón "Buscar".
     *
     * Este método permite filtrar los usuarios mostrados en la tabla según el
     * tipo de nivel (por ejemplo, "Administrador", "Recepcionista" o
     * "Trabajador"). Si el campo de tipo está vacío, se muestra una
     * advertencia. Si se encuentran coincidencias, se actualiza la tabla con
     * los resultados.
     *
     * En caso de no encontrar usuarios con el tipo indicado, se informa al
     * usuario.
     *
     */
    private void buscarPorRol() {
        // Obtener lista de roles desde la BD
        List<Rol> roles = control.traerRoles();

        if (roles == null || roles.isEmpty()) {
            FormUtils.mostrarMensaje("No hay roles disponibles en la base de datos.", "Error", "Rol");
            return;
        }

        // Crear un JComboBox con los nombres de los roles
        JComboBox<String> comboRoles = new JComboBox<>();
        for (Rol r : roles) {
            comboRoles.addItem(r.getNombre());
        }

        // Mostrar el combo en un JOptionPane
        int opcion = JOptionPane.showConfirmDialog(this, comboRoles,
                "Selecciona un rol", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (opcion == JOptionPane.OK_OPTION) {
            String rolSeleccionado = (String) comboRoles.getSelectedItem();

            DefaultTableModel modelo = (DefaultTableModel) tablaUsuarios.getModel();
            modelo.setRowCount(0);

            for (Usuarios u : control.traerUsuarios()) {
                if (u.getTipo_rol() != null && u.getTipo_rol().getNombre().equalsIgnoreCase(rolSeleccionado)) {
                    modelo.addRow(new Object[]{
                        u.getId(),
                        u.getNombre(),
                        u.getApellidos(),
                        u.getEmail(),
                        u.getTipo_rol().getNombre()
                    });
                }
            }
        }
    }

    /**
     * Elimina el usuario seleccionado en la tabla de usuarios.
     * <p>
     * Este método obtiene la fila seleccionada en la tabla
     * {@code tablaUsuarios}. Si hay una fila seleccionada, obtiene el ID del
     * usuario correspondiente, llama al método {@code borrarUsuario} de la capa
     * de control para eliminarlo, recarga la tabla y muestra un mensaje de
     * confirmación.
     * <p>
     * Si no hay ninguna fila seleccionada, muestra un mensaje indicando que se
     * debe seleccionar un usuario antes de eliminar.
     */
    private void eliminarUsuario() {
        int fila = tablaUsuarios.getSelectedRow();
        if (fila != -1) {
            int idUsuario = (int) tablaUsuarios.getValueAt(fila, 0);
            control.borrarUsuario(idUsuario);
            cargarTablaUsuarios();
            FormUtils.mostrarMensaje("Usuario eliminado correctamente.", "Info", "Eliminación correcta");
        } else {
            FormUtils.mostrarMensaje("Selecciona un usuario para eliminar.", "Error", "Eliminación ");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnModif;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerTodos;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsuarios;
    public javax.swing.JTextField txtApellidos;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables
}
